#!/bin/bash

# Задаём рабочую папку, 
# применяем переменные окружения для камеры и 
# запускаем указанное приложение, отвязав его от консоли
(cd /home/inauto/inmark/app && source /home/ubuntu/.profile && ./start_line_union) & 

echo "app is started"